modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
displayURL="https://discord.gg/b5MgRNb3D7"
logoFile="assets/dragonminez/dragonminez.png"
authors="${mod_authors}"
credits="Thanks to Toji71_ for helping us with the Builds, and CyaneaCapillata for supporting us on Patreon."
displayTest="MATCH_VERSION" # Checkea misma version en cliente y servidor
description='''${mod_description}'''

[[dependencies.${mod_id}]]
    modId="forge"
    mandatory=true
    versionRange="${forge_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="geckolib"
    mandatory=true
    versionRange="${geckolib_version_range}"
    ordering="NONE"
    side="BOTH"